version: '3.0'
services:
  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
  app-node:
    depends_on:
      - dynamodb-local
    image: banst/awscli
    container_name: app-node
    ports:
     - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
    command:
      dynamodb create-table --endpoint-url http://dynamodb-local:8000 --region us-west-2 --table-name Voteable --attribute-definitions AttributeName=Id,AttributeType=S AttributeName=Question,AttributeType=S --key-schema AttributeName=Id,KeyType=HASH AttributeName=Question,KeyType=RANGE --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5